### ISSUE TITLE
does this plugin exist for react native?

### ISSUE THREAD

**Issue by nschurmann** [transistorsoft/cordova-background-geolocation-broadcast-receiver#1]

**Comment by christocracy** [comment]
React Native integration is much better.  It's [built into the plugin itself](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationEventReceiver.java).  You interact with it via ["Headless JS"](https://facebook.github.io/react-native/docs/headless-js-android.html)

**Comment by nschurmann** [comment]
Does this works even if the user close the app?

**Comment by christocracy** [comment]
If you configure BackgroundGeolocation to `stopOnTerminate: false`, yes.
