### ISSUE TITLE
Get Plugin Config in onHeartbeat method

### ISSUE THREAD

**Issue by 152hq** [transistorsoft/cordova-background-geolocation-broadcast-receiver#4]
We are trying to use this plugin to write custom logic to ping server on heartbeat trigger. We would like to know how to get the plugin state (url, params) in the method.
 private void onHeartbeat(Context context, Intent intent) {
        try {
			// ?? how to get url, param of plugin config here
            JSONObject location = new JSONObject(intent.getStringExtra("location"));
			TSLog.logger.debug(location.toString());
        } catch (JSONException e) {
            TSLog.logger.error(TSLog.error(e.getMessage()));
        }
    }

**Comment by christocracy** [comment]
Please learn to use markdown syntax-highlighting.  There's a ling right on the bottom-left of TEXTAREA:  *Styling with Markdown is supported*

![](https://dl.dropboxusercontent.com/s/ncyo4sfrevd5tfj/Screenshot%202017-10-05%2019.29.01.png?dl=1)

```java
BackgroundGeolocation adapter = BackgroundGeolocation.getInstance(context, intent);
JSONObject state = adapter.getState();
String url = state.getString("url");
JSONObject params = state.getJSONObject("params");
```

**Comment by 152hq** [comment]
Worked. Thanks :)
