### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by K1N5L4Y3R** [transistorsoft/cordova-background-geolocation-broadcast-receiver#5]
Hi Chris,

Following our conversation in https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/472, I opened this just not to spam the original issue further.

Is this **only** meant to run native Java code on BackgroundGeolocation events? I'm asking because I already have some Javascript code which uses some other cordova plugins such as cordova-plugin-ble-central that I would like to "keep running" even when the app is terminated. Is this possible?

A little bit off topic perhaps, I have also considered writing my own background service (https://github.com/Red-Folder/bgs-core/wiki/Build-your-own-Background-Service). From your experience, do you think that could also work for my use case described in my coment on the issue I mention above?

**Comment by christocracy** [comment]
If you're using `cordova-background-geolocation-lt`, you *already* have a Service running.  No need to create your own.  I'm pretty sure `RedFolder` is obsolete now.

This plugin is designed for implementing custom Java code to run after your app is terminated, where only the BackgroundGeolocation service is running "Headless".  This plugin allows you to receive all the usual events from BackgroundGeolocation in the native environment (eg: `location`, `motionchange`, `heartbeat`, `geofence`, etc.

**Comment by K1N5L4Y3R** [comment]
Gotcha'. Thanks, closing this.
