### ISSUE TITLE
compatibility with last cordova-background-geolocation version?

### ISSUE THREAD

**Issue by profcav** [transistorsoft/cordova-background-geolocation-broadcast-receiver#6]
Hi
are you planning an update of this plugin?

...
platforms/android/src/com/transistorsoft/cordova/bggeo/EventReceiver.java:194: error: cannot find symbol
                    adapter.setConfig(geo_params, callback);
                           ^
  symbol:   method setConfig(JSONObject,TSCallback)
  location: variable adapter of type BackgroundGeolocation
...
7 errors

Thanks
Paolo

**Comment by christocracy** [comment]
No.  This plugin is now obsolete now that [Android Headless Mode](https://github.com/transistorsoft/cordova-background-geolocation-lt/wiki/Android-Headless-Mode) is integrated into the plugin itself.
